### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by SirYaro**
I'm not sure why it worked for you, but I was getting syntax errors for every 'if' statement where you used double bracket [[ condition ]]. So if you don't mind, I correct it and check on 7 different systems if I'll get any error. 
With my fix I get none :)

### CODE REVIEW

**Comment by fabiomux** [comment]
The difference is that the double square brackets are Bash built-in, while the single square is just a symbolic link to the `test` command. Isn't your shell Bash? That might be the reason.

**Comment by SirYaro** [comment]
> The difference is that the double square brackets are Bash built-in, while the single square is just a symbolic link to the `test` command. Isn't your shell Bash? That might be the reason.

Well... yes. But you have "sh" shell defined in the first line, and it raised an error anyway...

An example, how it looks on my box:
```
yaro@yaro-desktop2:~/Pobrane/open_yakuake_here$ sh install.sh --install
Starting procedure from install.sh
install.sh: 8: [[: not found
Parameters: 1
install.sh: 14: [[: not found
install.sh: 1: kde4-config: not found
Parameter: --install
Installing: open_yakuake_here.desktop
cp: nie można utworzyć zwykłego pliku 'ServiceMenus/': Nie jest katalogiem
Service Menu installed!
yaro@yaro-desktop2:~/Pobrane/open_yakuake_here$
```

**Comment by fabiomux** [comment]
Yes, `sh` is a mere link to the Bash interpreter, at least under (mostly?) Linux OSes, that's why I have no errors.
If you type `bash install.sh --install` it should work correctly for you.
But now I am curious to know where `sh` points to you, might you report the result of `ls -l /usr/bin/sh`? (or whatever your sh path is)

**Comment by SirYaro** [comment]
tbh I never use /bin/sh as my shell, so I was really surprise to see this:

```
yaro@yaro-desktop2:~/Pobrane$ which sh
/usr/bin/sh
yaro@yaro-desktop2:~/Pobrane$ ll /usr/bin/sh
lrwxrwxrwx 1 root root 4 gru  3  2020 /usr/bin/sh -> dash*
yaro@yaro-desktop2:~/Pobrane$ which dash
/usr/bin/dash
yaro@yaro-desktop2:~/Pobrane$ ll /usr/bin/dash
-rwxr-xr-x 1 root root 129816 lip 18  2019 /usr/bin/dash*
yaro@yaro-desktop2:~/Pobrane$
```

**Comment by fabiomux** [comment]
Similar to Bash, but not fully compatible, probably I should replace the sh reference with bash... would it be enough for you?

**Comment by SirYaro** [comment]
This patch provides what I did exactly to install your plugin...
I'd also need to mention I get it from https://store.kde.org/p/1669701. I didn't check it, but maybe there is an old version up there?

**Comment by fabiomux** [comment]
I uploaded it on KDE store/Plingo/... so it is directly available from the Dolphin install service dialog. It is the same version here.

**Comment by fabiomux** [comment]
Fixed also the open_konsole_here service menu replacing the double squares with the expr command. Uploaded to Pling and available!

**Pull request merged**
