### PR TITLE
added flatpak versions

### PR DESCRIPTION
**Pull request by trytomakeyouprivate**
Somehow there are file opening bugs, but executing works. Commands should be exactly the same

### CODE REVIEW

**Comment by trytomakeyouprivate** [comment]
thanks!

**Comment by fabiomux** [comment]
Thank you for your contribution, I am going to rework these files to keep them aligned with the other services listed here, and publish again on Pling :) !

**Comment by fabiomux** [comment]
Published everything!

**Comment by trytomakeyouprivate** [comment]
nice! thank you for this great addon!

**Comment by trytomakeyouprivate** [comment]
also, I find kde dolphin context menus very random. Do you know how to integrate this into the "share" menu?

**Comment by fabiomux** [comment]
I don't know if it would change in the future but as far as I know, the only way to show the services is either at the *root* of the contextual menu or inside the *Actions* menu.

**Pull request merged**
